<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>@yield('title','Workspace') · {{ $brandName }}</title><link rel="icon" type="image/png" href="{{ asset($brandLogo) }}">@vite(['resources/css/app.css','resources/js/app.js'])</head><body>
<aside class="sidebar" id="sidebar"><a class="brand" href="/dashboard"><img src="{{ asset($brandLogo) }}" class="logo" alt="Aldef Tech"><small>LEARNING MANAGEMENT SYSTEM</small></a><button class="btn small mobile-toggle" data-toggle-sidebar aria-controls="sidebar" aria-expanded="false">Close navigation</button>
<div class="navlabel">WORKSPACE</div>
@php($nav=[['/dashboard','Overview','grid'],['/courses','Explore courses','book'],['/certificates','Certificates','award']])
@foreach($nav as [$url,$label,$icon])<a class="sidelink {{ request()->is(ltrim($url,'/'))?'active':'' }}" href="{{ $url }}"><x-icon :name="$icon"/>{{ $label }}</a>@endforeach
@if(auth()->user()->canTeach())<div class="navlabel">ACADEMY MANAGEMENT</div>
@php($nav=[['courses','Courses','book'],['sections','Chapters','grid'],['lessons','Lessons & materials','book'],['quizzes','Quizzes & exams','check'],['questions','Question bank','grid'],['assignments','Assignments','book'],['announcements','Announcements','bell']])
@foreach($nav as [$resource,$label,$icon])<a class="sidelink {{ request()->is('manage/'.$resource.'*')?'active':'' }}" href="/manage/{{ $resource }}"><x-icon :name="$icon"/>{{ $label }}</a>@endforeach
<a class="sidelink {{ request()->is('submissions')?'active':'' }}" href="/submissions"><x-icon name="check"/>Submission review</a><a class="sidelink {{ request()->is('reports')?'active':'' }}" href="/reports"><x-icon name="chart"/>Reports & analytics</a>@endif
@if(auth()->user()->isAdmin())<div class="navlabel">ADMINISTRATION</div>@foreach(['users'=>'User management','categories'=>'Categories','enrollments'=>'Enrollments','certificate-templates'=>'Certificate templates'] as $resource=>$label)<a class="sidelink {{ request()->is('manage/'.$resource.'*')?'active':'' }}" href="/manage/{{ $resource }}"><x-icon name="{{ $resource==='users'?'users':'grid' }}"/>{{ $label }}</a>@endforeach<a class="sidelink {{ request()->is('activity')?'active':'' }}" href="/activity"><x-icon name="chart"/>Activity log</a><a class="sidelink {{ request()->is('settings')?'active':'' }}" href="/settings"><x-icon name="settings"/>Settings</a>@endif
<div class="sidebar-bottom">Built for your next chapter.<br><span style="color:#a1aac2">{{ $brandName }} · {{ date('Y') }}</span></div></aside>
<div class="app-main"><header class="app-header"><div class="row"><button class="btn secondary small mobile-toggle" data-toggle-sidebar aria-controls="sidebar" aria-expanded="false" aria-label="Open navigation">☰</button><div class="header-brand row"><img src="{{ asset($brandLogo) }}" alt="Aldef Tech" style="width:80px;height:32px;object-fit:contain"><span class="muted" style="font-size:12px;border-left:1px solid #e7e9f1;padding-left:17px">Your learning workspace</span></div></div><div class="row"><a href="/profile" class="row"><span class="avatar">{{ mb_substr(auth()->user()->name,0,1) }}</span><span><strong style="font-size:12px">{{ auth()->user()->name }}</strong><small style="display:block;font-size:10px">{{ \App\Models\User::ROLES[auth()->user()->role] }}</small></span></a><form method="POST" action="/logout">@csrf<button class="btn secondary small">Sign out</button></form></div></header>
<main class="app-content">@include('components.alerts')@yield('content')</main></div></body></html>
