<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>@yield('title','Workspace') · {{ $brandName }}</title><link rel="icon" type="image/png" href="{{ asset('assets/logo/aldef-landscape02.png') }}">@vite(['resources/css/app.css','resources/js/app.js'])</head><body>
<aside class="sidebar" id="sidebar"><a class="brand" href="{{ auth()->user()->dashboardPath() }}"><img src="{{ asset('assets/logo/aldef-landscape02.png') }}" class="logo" alt="Aldef Tech"><small>LEARNING MANAGEMENT SYSTEM</small></a><button class="btn small mobile-toggle" data-toggle-sidebar aria-controls="sidebar" aria-expanded="false">Close navigation</button>
<div class="navlabel">WORKSPACE</div>
<a class="sidelink {{ request()->is('dashboard*')?'active':'' }}" href="{{ auth()->user()->dashboardPath() }}"><x-icon name="grid"/>Overview</a>
@can('courses.view')<a class="sidelink {{ request()->is('courses')||request()->is('courses/*')?'active':'' }}" href="/courses"><x-icon name="book"/>Explore courses</a>@endcan
@canany(['certificates.view-own','certificates.manage','certificates.view-organization'])<a class="sidelink {{ request()->is('certificates*')?'active':'' }}" href="/certificates"><x-icon name="award"/>Certificates</a>@endcanany
@canany(['courses.manage','courses.manage-own','lessons.manage','lessons.manage-own','assessments.manage','assessments.manage-own'])
<div class="navlabel">ACADEMY MANAGEMENT</div>
@canany(['courses.manage','courses.manage-own'])<a class="sidelink {{ request()->is('manage/courses*')?'active':'' }}" href="/manage/courses"><x-icon name="book"/>Courses</a>@endcanany
@canany(['lessons.manage','lessons.manage-own'])<a class="sidelink {{ request()->is('manage/sections*')?'active':'' }}" href="/manage/sections"><x-icon name="grid"/>Chapters</a><a class="sidelink {{ request()->is('manage/lessons*')?'active':'' }}" href="/manage/lessons"><x-icon name="book"/>Lessons & materials</a>@endcanany
@canany(['assessments.manage','assessments.manage-own'])<a class="sidelink {{ request()->is('manage/quizzes*')?'active':'' }}" href="/manage/quizzes"><x-icon name="check"/>Quizzes & exams</a><a class="sidelink {{ request()->is('manage/questions*')?'active':'' }}" href="/manage/questions"><x-icon name="grid"/>Question bank</a><a class="sidelink {{ request()->is('manage/assignments*')?'active':'' }}" href="/manage/assignments"><x-icon name="book"/>Assignments</a>@endcanany
@canany(['announcements.manage','announcements.manage-own'])<a class="sidelink {{ request()->is('manage/announcements*')?'active':'' }}" href="/manage/announcements"><x-icon name="bell"/>Announcements</a>@endcanany
@can('grading.manage-own')<a class="sidelink {{ request()->is('submissions')?'active':'' }}" href="/submissions"><x-icon name="check"/>Submission review</a>@endcan
@canany(['reports.view','reports.view-own'])<a class="sidelink {{ request()->is('reports')?'active':'' }}" href="/reports"><x-icon name="chart"/>Reports & analytics</a>@endcanany
@endcanany
@canany(['users.manage','enrollments.manage','enrollments.manage-organization','organizations.manage','organizations.manage-own'])
<div class="navlabel">{{ auth()->user()->isCorporateAdmin()?'ORGANIZATION':'ADMINISTRATION' }}</div>
@can('users.manage')<a class="sidelink {{ request()->is('manage/users*')?'active':'' }}" href="/manage/users"><x-icon name="users"/>{{ auth()->user()->isCorporateAdmin()?'Organization members':'User management' }}</a>@endcan
@canany(['enrollments.manage','enrollments.manage-organization'])<a class="sidelink {{ request()->is('manage/enrollments*')?'active':'' }}" href="/manage/enrollments"><x-icon name="grid"/>Enrollments</a>@endcanany
@canany(['organizations.manage','organizations.manage-own'])<a class="sidelink {{ request()->is('manage/organizations*')?'active':'' }}" href="/manage/organizations"><x-icon name="grid"/>Organization</a>@endcanany
@can('courses.manage')<a class="sidelink {{ request()->is('manage/categories*')?'active':'' }}" href="/manage/categories"><x-icon name="grid"/>Categories</a>@endcan
@can('certificates.manage')<a class="sidelink {{ request()->is('manage/certificate-templates*')?'active':'' }}" href="/manage/certificate-templates"><x-icon name="award"/>Certificate templates</a>@endcan
@can('reports.view-organization')<a class="sidelink {{ request()->is('reports')?'active':'' }}" href="/reports"><x-icon name="chart"/>Organization report</a>@endcan
@can('roles.manage')<a class="sidelink {{ request()->is('rbac*')?'active':'' }}" href="/rbac"><x-icon name="users"/>Roles & permissions</a>@endcan
@can('audit.view')<a class="sidelink {{ request()->is('activity')?'active':'' }}" href="/activity"><x-icon name="chart"/>Audit log</a>@endcan
@can('settings.manage')<a class="sidelink {{ request()->is('settings')?'active':'' }}" href="/settings"><x-icon name="settings"/>Settings</a>@endcan
@endcanany
<div class="sidebar-bottom">Built for your next chapter.<br><span style="color:#a1aac2">{{ $brandName }} · {{ date('Y') }}</span></div></aside>
<div class="app-main"><header class="app-header"><div class="row"><button class="btn secondary small mobile-toggle" data-toggle-sidebar aria-controls="sidebar" aria-expanded="false" aria-label="Open navigation">☰</button><div class="header-brand row"><img src="{{ asset('assets/logo/aldef-landscape02.png') }}" alt="Aldef Tech" style="width:80px;height:32px;object-fit:contain"><span class="muted" style="font-size:12px;border-left:1px solid #e7e9f1;padding-left:17px">Your learning workspace</span></div></div><div class="row"><a href="/profile" class="row"><span class="avatar">{{ mb_substr(auth()->user()->name,0,1) }}</span><span><strong style="font-size:12px">{{ auth()->user()->name }}</strong><small style="display:block;font-size:10px">{{ auth()->user()->roleName() }}</small></span></a><form method="POST" action="/logout">@csrf<button class="btn secondary small">Sign out</button></form></div></header>
<main class="app-content">@include('components.alerts')@yield('content')</main></div></body></html>
